// Generated from static App Router page files by scripts/generate-site-search-routes.mjs.
export const generatedSearchRoutes = [
    {
        id: 'route:/',
        title: 'Home',
        detail: 'Overview and product entry point',
        href: '/',
    },
    {
        id: 'route:/about',
        title: 'About',
        detail: 'Page · /about',
        href: '/about',
    },
    {
        id: 'route:/account-pending-deletion',
        title: 'Account Pending Deletion',
        detail: 'Page · /account-pending-deletion',
        href: '/account-pending-deletion',
    },
    {
        id: 'route:/activity',
        title: 'Activity',
        detail: 'Page · /activity',
        href: '/activity',
    },
    {
        id: 'route:/ai',
        title: 'Ai',
        detail: 'Page · /ai',
        href: '/ai',
    },
    {
        id: 'route:/ai/window',
        title: 'Ai · Window',
        detail: 'Page · /ai/window',
        href: '/ai/window',
    },
    {
        id: 'route:/api',
        title: 'Api',
        detail: 'Page · /api',
        href: '/api',
    },
    {
        id: 'route:/api/openapi',
        title: 'Api · Openapi',
        detail: 'Page · /api/openapi',
        href: '/api/openapi',
    },
    {
        id: 'route:/article',
        title: 'Article',
        detail: 'Page · /article',
        href: '/article',
    },
    {
        id: 'route:/articles',
        title: 'Articles',
        detail: 'Page · /articles',
        href: '/articles',
    },
    {
        id: 'route:/browser',
        title: 'Browser',
        detail: 'Page · /browser',
        href: '/browser',
    },
    {
        id: 'route:/browser-sandbox',
        title: 'Browser Sandbox',
        detail: 'Page · /browser-sandbox',
        href: '/browser-sandbox',
    },
    {
        id: 'route:/contact',
        title: 'Contact',
        detail: 'Page · /contact',
        href: '/contact',
    },
    {
        id: 'route:/cookie-settings',
        title: 'Cookie Settings',
        detail: 'Page · /cookie-settings',
        href: '/cookie-settings',
    },
    {
        id: 'route:/cookies',
        title: 'Cookies',
        detail: 'Page · /cookies',
        href: '/cookies',
    },
    {
        id: 'route:/dashboard',
        title: 'Dashboard',
        detail: 'Page · /dashboard',
        href: '/dashboard',
    },
    {
        id: 'route:/dashboard/api-docs',
        title: 'Dashboard · Api Docs',
        detail: 'Page · /dashboard/api-docs',
        href: '/dashboard/api-docs',
    },
    {
        id: 'route:/dashboard/article',
        title: 'Dashboard · Article',
        detail: 'Page · /dashboard/article',
        href: '/dashboard/article',
    },
    {
        id: 'route:/dashboard/articles',
        title: 'Dashboard · Articles',
        detail: 'Page · /dashboard/articles',
        href: '/dashboard/articles',
    },
    {
        id: 'route:/dashboard/articles/create',
        title: 'Dashboard · Articles · Create',
        detail: 'Page · /dashboard/articles/create',
        href: '/dashboard/articles/create',
    },
    {
        id: 'route:/dashboard/automation',
        title: 'Dashboard · Automation',
        detail: 'Page · /dashboard/automation',
        href: '/dashboard/automation',
    },
    {
        id: 'route:/dashboard/automation/cron',
        title: 'Dashboard · Automation · Cron',
        detail: 'Page · /dashboard/automation/cron',
        href: '/dashboard/automation/cron',
    },
    {
        id: 'route:/dashboard/automation/health',
        title: 'Dashboard · Automation · Health',
        detail: 'Page · /dashboard/automation/health',
        href: '/dashboard/automation/health',
    },
    {
        id: 'route:/dashboard/automation/monitoring',
        title: 'Dashboard · Automation · Monitoring',
        detail: 'Page · /dashboard/automation/monitoring',
        href: '/dashboard/automation/monitoring',
    },
    {
        id: 'route:/dashboard/backup',
        title: 'Dashboard · Backup',
        detail: 'Page · /dashboard/backup',
        href: '/dashboard/backup',
    },
    {
        id: 'route:/dashboard/cases',
        title: 'Dashboard · Cases',
        detail: 'Page · /dashboard/cases',
        href: '/dashboard/cases',
    },
    {
        id: 'route:/dashboard/db',
        title: 'Dashboard · Db',
        detail: 'Page · /dashboard/db',
        href: '/dashboard/db',
    },
    {
        id: 'route:/dashboard/db/backups',
        title: 'Dashboard · Db · Backups',
        detail: 'Page · /dashboard/db/backups',
        href: '/dashboard/db/backups',
    },
    {
        id: 'route:/dashboard/db/restore',
        title: 'Dashboard · Db · Restore',
        detail: 'Page · /dashboard/db/restore',
        href: '/dashboard/db/restore',
    },
    {
        id: 'route:/dashboard/findings',
        title: 'Dashboard · Findings',
        detail: 'Page · /dashboard/findings',
        href: '/dashboard/findings',
    },
    {
        id: 'route:/dashboard/findings/actions',
        title: 'Dashboard · Findings · Actions',
        detail: 'Page · /dashboard/findings/actions',
        href: '/dashboard/findings/actions',
    },
    {
        id: 'route:/dashboard/findings/actors',
        title: 'Dashboard · Findings · Actors',
        detail: 'Page · /dashboard/findings/actors',
        href: '/dashboard/findings/actors',
    },
    {
        id: 'route:/dashboard/findings/alerts',
        title: 'Dashboard · Findings · Alerts',
        detail: 'Page · /dashboard/findings/alerts',
        href: '/dashboard/findings/alerts',
    },
    {
        id: 'route:/dashboard/findings/cases',
        title: 'Dashboard · Findings · Cases',
        detail: 'Page · /dashboard/findings/cases',
        href: '/dashboard/findings/cases',
    },
    {
        id: 'route:/dashboard/findings/delivery',
        title: 'Dashboard · Findings · Delivery',
        detail: 'Page · /dashboard/findings/delivery',
        href: '/dashboard/findings/delivery',
    },
    {
        id: 'route:/dashboard/findings/sources',
        title: 'Dashboard · Findings · Sources',
        detail: 'Page · /dashboard/findings/sources',
        href: '/dashboard/findings/sources',
    },
    {
        id: 'route:/watchlists',
        title: 'Watchlists',
        detail: 'Page · /watchlists',
        href: '/watchlists',
    },
    {
        id: 'route:/dashboard/helpdesk',
        title: 'Dashboard · Helpdesk',
        detail: 'Page · /dashboard/helpdesk',
        href: '/dashboard/helpdesk',
    },
    {
        id: 'route:/dashboard/load-testing',
        title: 'Dashboard · Load Testing',
        detail: 'Page · /dashboard/load-testing',
        href: '/dashboard/load-testing',
    },
    {
        id: 'route:/dashboard/logs',
        title: 'Dashboard · Logs',
        detail: 'Page · /dashboard/logs',
        href: '/dashboard/logs',
    },
    {
        id: 'route:/dashboard/logs/errors',
        title: 'Dashboard · Logs · Errors',
        detail: 'Page · /dashboard/logs/errors',
        href: '/dashboard/logs/errors',
    },
    {
        id: 'route:/dashboard/logs/realtime',
        title: 'Dashboard · Logs · Realtime',
        detail: 'Page · /dashboard/logs/realtime',
        href: '/dashboard/logs/realtime',
    },
    {
        id: 'route:/dashboard/logs/search',
        title: 'Dashboard · Logs · Search',
        detail: 'Page · /dashboard/logs/search',
        href: '/dashboard/logs/search',
    },
    {
        id: 'route:/dashboard/mail',
        title: 'Dashboard · Mail',
        detail: 'Page · /dashboard/mail',
        href: '/dashboard/mail',
    },
    {
        id: 'route:/dashboard/management',
        title: 'Dashboard · Management',
        detail: 'Page · /dashboard/management',
        href: '/dashboard/management',
    },
    {
        id: 'route:/dashboard/management/audit',
        title: 'Dashboard · Management · Audit',
        detail: 'Page · /dashboard/management/audit',
        href: '/dashboard/management/audit',
    },
    {
        id: 'route:/dashboard/management/organizations',
        title: 'Dashboard · Management · Organizations',
        detail: 'Page · /dashboard/management/organizations',
        href: '/dashboard/management/organizations',
    },
    {
        id: 'route:/dashboard/management/service-accounts',
        title: 'Dashboard · Management · Service Accounts',
        detail: 'Page · /dashboard/management/service-accounts',
        href: '/dashboard/management/service-accounts',
    },
    {
        id: 'route:/dashboard/management/users',
        title: 'Dashboard · Management · Users',
        detail: 'Page · /dashboard/management/users',
        href: '/dashboard/management/users',
    },
    {
        id: 'route:/dashboard/notes',
        title: 'Dashboard · Notes',
        detail: 'Page · /dashboard/notes',
        href: '/dashboard/notes',
    },
    {
        id: 'route:/dashboard/overview',
        title: 'Dashboard · Overview',
        detail: 'Page · /dashboard/overview',
        href: '/dashboard/overview',
    },
    {
        id: 'route:/dashboard/projects',
        title: 'Dashboard · Projects',
        detail: 'Page · /dashboard/projects',
        href: '/dashboard/projects',
    },
    {
        id: 'route:/dashboard/rules',
        title: 'Dashboard · Rules',
        detail: 'Page · /dashboard/rules',
        href: '/dashboard/rules',
    },
    {
        id: 'route:/dashboard/rules/analysis',
        title: 'Dashboard · Rules · Analysis',
        detail: 'Page · /dashboard/rules/analysis',
        href: '/dashboard/rules/analysis',
    },
    {
        id: 'route:/dashboard/rules/detection',
        title: 'Dashboard · Rules · Detection',
        detail: 'Page · /dashboard/rules/detection',
        href: '/dashboard/rules/detection',
    },
    {
        id: 'route:/dashboard/rules/match',
        title: 'Dashboard · Rules · Match',
        detail: 'Page · /dashboard/rules/match',
        href: '/dashboard/rules/match',
    },
    {
        id: 'route:/dashboard/scanner',
        title: 'Dashboard · Scanner',
        detail: 'Page · /dashboard/scanner',
        href: '/dashboard/scanner',
    },
    {
        id: 'route:/dashboard/shares',
        title: 'Dashboard · Shares',
        detail: 'Page · /dashboard/shares',
        href: '/dashboard/shares',
    },
    {
        id: 'route:/dashboard/subscription',
        title: 'Dashboard · Subscription',
        detail: 'Page · /dashboard/subscription',
        href: '/dashboard/subscription',
    },
    {
        id: 'route:/dashboard/system',
        title: 'Dashboard · System',
        detail: 'Page · /dashboard/system',
        href: '/dashboard/system',
    },
    {
        id: 'route:/dashboard/system/ai',
        title: 'Dashboard · System · Ai',
        detail: 'Page · /dashboard/system/ai',
        href: '/dashboard/system/ai',
    },
    {
        id: 'route:/dashboard/system/console',
        title: 'Dashboard · System · Console',
        detail: 'Page · /dashboard/system/console',
        href: '/dashboard/system/console',
    },
    {
        id: 'route:/dashboard/system/hosts',
        title: 'Dashboard · System · Hosts',
        detail: 'Page · /dashboard/system/hosts',
        href: '/dashboard/system/hosts',
    },
    {
        id: 'route:/dashboard/system/impersonation',
        title: 'Dashboard · System · Impersonation',
        detail: 'Page · /dashboard/system/impersonation',
        href: '/dashboard/system/impersonation',
    },
    {
        id: 'route:/dashboard/system/rates',
        title: 'Dashboard · System · Rates',
        detail: 'Page · /dashboard/system/rates',
        href: '/dashboard/system/rates',
    },
    {
        id: 'route:/dashboard/system/updates',
        title: 'Dashboard · System · Updates',
        detail: 'Page · /dashboard/system/updates',
        href: '/dashboard/system/updates',
    },
    {
        id: 'route:/dashboard/thesis',
        title: 'Dashboard · Thesis',
        detail: 'Page · /dashboard/thesis',
        href: '/dashboard/thesis',
    },
    {
        id: 'route:/dashboard/thought',
        title: 'Dashboard · Thought',
        detail: 'Page · /dashboard/thought',
        href: '/dashboard/thought',
    },
    {
        id: 'route:/dashboard/thought/create',
        title: 'Dashboard · Thought · Create',
        detail: 'Page · /dashboard/thought/create',
        href: '/dashboard/thought/create',
    },
    {
        id: 'route:/dashboard/thoughts',
        title: 'Dashboard · Thoughts',
        detail: 'Page · /dashboard/thoughts',
        href: '/dashboard/thoughts',
    },
    {
        id: 'route:/dashboard/thoughts/create',
        title: 'Dashboard · Thoughts · Create',
        detail: 'Page · /dashboard/thoughts/create',
        href: '/dashboard/thoughts/create',
    },
    {
        id: 'route:/dashboard/ti',
        title: 'Dashboard · Ti',
        detail: 'Page · /dashboard/ti',
        href: '/dashboard/ti',
    },
    {
        id: 'route:/dashboard/ti/activity',
        title: 'Dashboard · Ti · Activity',
        detail: 'Page · /dashboard/ti/activity',
        href: '/dashboard/ti/activity',
    },
    {
        id: 'route:/dashboard/ti/audit',
        title: 'Dashboard · Ti · Audit',
        detail: 'Page · /dashboard/ti/audit',
        href: '/dashboard/ti/audit',
    },
    {
        id: 'route:/dashboard/ti/control',
        title: 'Dashboard · Ti · Control',
        detail: 'Page · /dashboard/ti/control',
        href: '/dashboard/ti/control',
    },
    {
        id: 'route:/dashboard/ti/evaluation',
        title: 'Dashboard · Ti · Evaluation',
        detail: 'Page · /dashboard/ti/evaluation',
        href: '/dashboard/ti/evaluation',
    },
    {
        id: 'route:/dashboard/ti/runs',
        title: 'Dashboard · Ti · Runs',
        detail: 'Page · /dashboard/ti/runs',
        href: '/dashboard/ti/runs',
    },
    {
        id: 'route:/dashboard/ti/sources',
        title: 'Dashboard · Ti · Sources',
        detail: 'Page · /dashboard/ti/sources',
        href: '/dashboard/ti/sources',
    },
    {
        id: 'route:/dashboard/ti/timeliness',
        title: 'Dashboard · Ti · Timeliness',
        detail: 'Page · /dashboard/ti/timeliness',
        href: '/dashboard/ti/timeliness',
    },
    {
        id: 'route:/dashboard/ti/workbench',
        title: 'Dashboard · Ti · Workbench',
        detail: 'Page · /dashboard/ti/workbench',
        href: '/dashboard/ti/workbench',
    },
    {
        id: 'route:/dashboard/traffic',
        title: 'Dashboard · Traffic',
        detail: 'Page · /dashboard/traffic',
        href: '/dashboard/traffic',
    },
    {
        id: 'route:/dashboard/traffic/blocklist',
        title: 'Dashboard · Traffic · Blocklist',
        detail: 'Page · /dashboard/traffic/blocklist',
        href: '/dashboard/traffic/blocklist',
    },
    {
        id: 'route:/dashboard/traffic/map',
        title: 'Dashboard · Traffic · Map',
        detail: 'Page · /dashboard/traffic/map',
        href: '/dashboard/traffic/map',
    },
    {
        id: 'route:/dashboard/traffic/recent',
        title: 'Dashboard · Traffic · Recent',
        detail: 'Page · /dashboard/traffic/recent',
        href: '/dashboard/traffic/recent',
    },
    {
        id: 'route:/dashboard/vm',
        title: 'Dashboard · Vm',
        detail: 'Page · /dashboard/vm',
        href: '/dashboard/vm',
    },
    {
        id: 'route:/dashboard/vms',
        title: 'Dashboard · Vms',
        detail: 'Page · /dashboard/vms',
        href: '/dashboard/vms',
    },
    {
        id: 'route:/dashboard/vulnerabilities',
        title: 'Dashboard · Vulnerabilities',
        detail: 'Page · /dashboard/vulnerabilities',
        href: '/dashboard/vulnerabilities',
    },
    {
        id: 'route:/developers',
        title: 'Developers',
        detail: 'Page · /developers',
        href: '/developers',
    },
    {
        id: 'route:/faq',
        title: 'Faq',
        detail: 'Page · /faq',
        href: '/faq',
    },
    {
        id: 'route:/g',
        title: 'G',
        detail: 'Page · /g',
        href: '/g',
    },
    {
        id: 'route:/g/stats',
        title: 'G · Stats',
        detail: 'Page · /g/stats',
        href: '/g/stats',
    },
    {
        id: 'route:/gallery',
        title: 'Gallery',
        detail: 'Page · /gallery',
        href: '/gallery',
    },
    {
        id: 'route:/login',
        title: 'Login',
        detail: 'Page · /login',
        href: '/login',
    },
    {
        id: 'route:/logout',
        title: 'Logout',
        detail: 'Page · /logout',
        href: '/logout',
    },
    {
        id: 'route:/monitor',
        title: 'Monitor',
        detail: 'Page · /monitor',
        href: '/monitor',
    },
    {
        id: 'route:/notes',
        title: 'Notes',
        detail: 'Page · /notes',
        href: '/notes',
    },
    {
        id: 'route:/onion-session',
        title: 'Onion Session',
        detail: 'Page · /onion-session',
        href: '/onion-session',
    },
    {
        id: 'route:/organizations',
        title: 'Organizations',
        detail: 'Page · /organizations',
        href: '/organizations',
    },
    {
        id: 'route:/pricing',
        title: 'Pricing',
        detail: 'Page · /pricing',
        href: '/pricing',
    },
    {
        id: 'route:/privacy',
        title: 'Privacy',
        detail: 'Page · /privacy',
        href: '/privacy',
    },
    {
        id: 'route:/profile',
        title: 'Profile',
        detail: 'Page · /profile',
        href: '/profile',
    },
    {
        id: 'route:/prompt',
        title: 'Prompt',
        detail: 'Page · /prompt',
        href: '/prompt',
    },
    {
        id: 'route:/pwned',
        title: 'Pwned',
        detail: 'Page · /pwned',
        href: '/pwned',
    },
    {
        id: 'route:/register',
        title: 'Register',
        detail: 'Page · /register',
        href: '/register',
    },
    {
        id: 'route:/reserved-usernames',
        title: 'Reserved Usernames',
        detail: 'Page · /reserved-usernames',
        href: '/reserved-usernames',
    },
    {
        id: 'route:/reset-password',
        title: 'Reset Password',
        detail: 'Page · /reset-password',
        href: '/reset-password',
    },
    {
        id: 'route:/reset-password-again',
        title: 'Reset Password Again',
        detail: 'Page · /reset-password-again',
        href: '/reset-password-again',
    },
    {
        id: 'route:/s',
        title: 'S',
        detail: 'Page · /s',
        href: '/s',
    },
    {
        id: 'route:/secure-account',
        title: 'Secure Account',
        detail: 'Page · /secure-account',
        href: '/secure-account',
    },
    {
        id: 'route:/signup',
        title: 'Signup',
        detail: 'Page · /signup',
        href: '/signup',
    },
    {
        id: 'route:/solutions/onion-session',
        title: 'Solutions · Onion Session',
        detail: 'Page · /solutions/onion-session',
        href: '/solutions/onion-session',
    },
    {
        id: 'route:/solutions/scanner',
        title: 'Solutions · Scanner',
        detail: 'Page · /solutions/scanner',
        href: '/solutions/scanner',
    },
    {
        id: 'route:/solutions/security-monitoring',
        title: 'Solutions · Security Monitoring',
        detail: 'Page · /solutions/security-monitoring',
        href: '/solutions/security-monitoring',
    },
    {
        id: 'route:/status',
        title: 'Status',
        detail: 'Page · /status',
        href: '/status',
    },
    {
        id: 'route:/status/incidents',
        title: 'Status · Incidents',
        detail: 'Page · /status/incidents',
        href: '/status/incidents',
    },
    {
        id: 'route:/support',
        title: 'Support',
        detail: 'Page · /support',
        href: '/support',
    },
    {
        id: 'route:/switch-account',
        title: 'Switch Account',
        detail: 'Page · /switch-account',
        href: '/switch-account',
    },
    {
        id: 'route:/terms',
        title: 'Terms',
        detail: 'Page · /terms',
        href: '/terms',
    },
    {
        id: 'route:/test',
        title: 'Test',
        detail: 'Page · /test',
        href: '/test',
    },
    {
        id: 'route:/test/stats',
        title: 'Test · Stats',
        detail: 'Page · /test/stats',
        href: '/test/stats',
    },
    {
        id: 'route:/thesis',
        title: 'Thesis',
        detail: 'Page · /thesis',
        href: '/thesis',
    },
    {
        id: 'route:/ti',
        title: 'Ti',
        detail: 'Page · /ti',
        href: '/ti',
    },
    {
        id: 'route:/ti/darkweb/index',
        title: 'Ti · Darkweb · Index',
        detail: 'Page · /ti/darkweb/index',
        href: '/ti/darkweb/index',
    },
    {
        id: 'route:/ti/profiles',
        title: 'Ti · Profiles',
        detail: 'Page · /ti/profiles',
        href: '/ti/profiles',
    },
    {
        id: 'route:/upload',
        title: 'Upload',
        detail: 'Page · /upload',
        href: '/upload',
    },
    {
        id: 'route:/user',
        title: 'User',
        detail: 'Page · /user',
        href: '/user',
    },
    {
        id: 'route:/users',
        title: 'Users',
        detail: 'Page · /users',
        href: '/users',
    }
] as const
