import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const backupPage = await source('../src/app/dashboard/db/backups/backupPage.tsx')
const backupRoute = await source('../src/app/dashboard/db/backups/page.tsx')
const restoreClient = await source('../src/app/dashboard/db/restore/restoreClient.tsx')
const restoreRoute = await source('../src/app/dashboard/db/restore/page.tsx')
const actions = await source('../src/app/dashboard/db/actions.ts')
const frontendApi = await source('../src/utils/db/internal.ts')
const serviceApi = await source('../src/utils/monitoring/serviceApi.ts')
const apiRoutes = await source('../../api/src/routes.ts')
const apiHandler = await source('../../api/src/handlers/database/backups.ts')
const apiCore = await source('../../api/src/utils/db/backups.ts')
const apiCron = await source('../../api/src/utils/cron.ts')
const compose = await source('../../docker-compose.yml')
const dockerfile = await source('../../api/Dockerfile')

assert.match(backupRoute, /Promise\.all\(\[getBackupServices\(\), getBackupFiles\(\)\]\)/, 'backup route must load status and measured files together')
assert.match(backupPage, /Last attempt/)
assert.match(backupPage, /Last success/)
assert.match(backupPage, /Last failure/)
assert.match(backupPage, /Next automatic run/)
assert.match(backupPage, /Storage target/)
assert.match(backupPage, /Latest checksum/)
assert.match(backupPage, /History/)
assert.match(backupPage, /verifyBackupAction\(file\)/, 'operators must be able to recompute archive verification')
assert.match(backupPage, /service\.currentOperation/, 'UI must expose backend operation progress rather than a fake completed state')
assert.doesNotMatch(backupPage, /s3:\/\/|DB_BACKUP_NEXT_AT|restore readiness/, 'operator evidence must not be guessed or sample-backed')

assert.match(restoreRoute, /Promise\.all\(\[getBackupFiles\([\s\S]*getBackupServices\(\)\]\)/, 'restore route must load files and live operation progress')
assert.match(restoreClient, /Isolated target database/)
assert.match(restoreClient, /confirmation === requiredConfirmation/)
assert.match(restoreClient, /restoreBackupAction\(file, target, confirmation\)/)
assert.match(restoreClient, /This workflow never restores over the live database/)
assert.match(restoreClient, /creating_isolated_database/)
assert.match(restoreClient, /checking_integrity/)
assert.match(restoreClient, /removing_isolated_database/)
assert.match(restoreClient, /Restore-drill audit history/)
assert.doesNotMatch(restoreClient, /DB_RESTORE_ENABLED|blocked/i, 'restore UI must drive the real isolated workflow, not a generic blocker')

assert.match(actions, /verifyDatabaseBackup/)
assert.match(actions, /restoreDatabaseBackup\(file, targetDatabase, confirmation\)/)
assert.match(actions, /updateTag\('database-backups'\)/, 'completed backup changes must invalidate the cached view')
assert.match(frontendApi, /requestService<BackupService\[\]>\('internal', 'backup', undefined, backupDataCache\)/)
assert.match(frontendApi, /export async function getBackupFiles[\s\S]*?backupDataCache/)
assert.match(frontendApi, /revalidate: 30, tags: \['database-backups'\]/)
assert.match(serviceApi, /tags: cacheOptions\.tags/)
assert.match(frontendApi, /'backup\/verify'/)
assert.match(frontendApi, /JSON\.stringify\(\{ file, targetDatabase, confirmation \}\)/)
assert.match(apiRoutes, /fastify\.post\('\/backup\/verify', postDatabaseBackupVerify\)/)
assert.match(apiRoutes, /fastify\.post\('\/backup\/restore', postDatabaseBackupRestore\)/)
assert.match(apiHandler, /hasHanasandInternalRouteAccess\(req\)/)
assert.match(apiHandler, /targetDatabase: req\.body\.targetDatabase/)
assert.match(apiCore, /open\(lock, 'wx'/, 'overlapping operations must use an exclusive persisted lock')
assert.doesNotMatch(apiCore, /pg_database_size/, 'loading backup status must not query the full live database size')
assert.match(apiCore, /checksumSha256/)
assert.match(apiCore, /pg_restore', \['--list'/, 'archives must be verified with PostgreSQL native tooling')
assert.match(apiCore, /restore_drill_/)
assert.match(apiCore, /'createdb'/)
assert.match(apiCore, /'dropdb'/)
assert.match(apiCore, /targetRemoved: true/)
assert.doesNotMatch(apiCore, /--clean[\s\S]*databaseName\(\)/, 'the product must not expose a destructive live restore implementation')
assert.match(apiCron, /runDueDatabaseBackup/)
assert.match(compose, /api_state:\/var\/lib\/hanasand/)
assert.match(compose, /DB_BACKUP_SCHEDULE: \$\{DB_BACKUP_SCHEDULE:-23 2 \* \* \*\}/)
assert.match(compose, /DB_BACKUP_RETENTION_DAYS: \$\{DB_BACKUP_RETENTION_DAYS:-63\}/)
assert.match(apiCore, /RECENT_RETENTION_DAYS = 3/)
assert.match(apiCore, /WEEKLY_RETENTION_WEEKS = 8/)
assert.match(apiCore, /startOfUtcWeek/)
assert.match(frontendApi, /slots: string\[\]/)
assert.match(dockerfile, /postgresql-client/)

console.log('Backup operator workflow checks passed.')

async function source(relative: string) {
    return readFile(new URL(relative, import.meta.url), 'utf8')
}
