import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const backupPage = await source('../src/app/dashboard/db/backups/backupPage.tsx')
const backupRoute = await source('../src/app/dashboard/db/backups/page.tsx')
const restoreClient = await source('../src/app/dashboard/db/restore/restoreClient.tsx')
const restoreRoute = await source('../src/app/dashboard/db/restore/page.tsx')
const actions = await source('../src/app/dashboard/db/actions.ts')
const frontendApi = await source('../src/utils/db/internal.ts')
const serviceApi = await source('../src/utils/monitoring/serviceApi.ts')
const apiRoutes = await source('../../api/src/routes.ts')
const apiHandler = await source('../../api/src/handlers/database/backups.ts')
const apiCore = await source('../../api/src/utils/db/backups.ts')
const backupWorkerClient = await source('../../api/src/utils/db/backupWorkerClient.ts')
const apiCron = await source('../../api/src/utils/cron.ts')
const compose = await source('../../docker-compose.yml')

assert.match(backupRoute, /Promise\.all\(\[getBackupServices\(\), getBackupFiles\(\)\]\)/, 'backup route must load status and measured files together')
assert.match(backupPage, /Last attempt/)
assert.match(backupPage, /Last success/)
assert.match(backupPage, /Last failure/)
assert.match(backupPage, /Next automatic run/)
assert.match(backupPage, /Storage target/)
assert.match(backupPage, /Latest checksum/)
assert.match(backupPage, /History/)
assert.match(backupPage, /verifyBackupAction\(file\)/, 'operators must be able to recompute archive verification')
assert.match(backupPage, /service\.currentOperation/, 'UI must expose backend operation progress rather than a fake completed state')
assert.doesNotMatch(backupPage, /s3:\/\/|DB_BACKUP_NEXT_AT|restore readiness/, 'operator evidence must not be guessed or sample-backed')

assert.match(restoreRoute, /Promise\.all\(\[getBackupFiles\([\s\S]*getBackupServices\(\)\]\)/, 'restore route must load files and live operation progress')
assert.match(restoreClient, /Isolated target database/)
assert.match(restoreClient, /confirmation === requiredConfirmation/)
assert.match(restoreClient, /restoreBackupAction\(file, target, confirmation\)/)
assert.match(restoreClient, /This workflow never restores over the live database/)
assert.match(restoreClient, /creating_isolated_database/)
assert.match(restoreClient, /checking_integrity/)
assert.match(restoreClient, /removing_isolated_database/)
assert.match(restoreClient, /Restore-drill audit history/)
assert.doesNotMatch(restoreClient, /DB_RESTORE_ENABLED|blocked/i, 'restore UI must drive the real isolated workflow, not a generic blocker')

assert.match(actions, /verifyDatabaseBackup/)
assert.match(actions, /restoreDatabaseBackup\(file, targetDatabase, confirmation\)/)
assert.match(actions, /updateTag\('database-backups'\)/, 'completed backup changes must invalidate the cached view')
assert.match(frontendApi, /requestService<BackupService\[\]>\('internal', 'backup', undefined, backupDataCache\)/)
assert.match(frontendApi, /export async function getBackupFiles[\s\S]*?backupDataCache/)
assert.match(frontendApi, /revalidate: 30, tags: \['database-backups'\]/)
assert.match(serviceApi, /tags: cacheOptions\.tags/)
assert.match(frontendApi, /'backup\/verify'/)
assert.match(frontendApi, /JSON\.stringify\(\{ file, targetDatabase, confirmation \}\)/)
assert.match(apiRoutes, /fastify\.post\('\/backup\/verify', postDatabaseBackupVerify\)/)
assert.match(apiRoutes, /fastify\.post\('\/backup\/restore', postDatabaseBackupRestore\)/)
assert.match(apiHandler, /hasHanasandInternalRouteAccess\(req\)/)
assert.match(apiHandler, /targetDatabase: req\.body\.targetDatabase/)
assert.match(apiCore, /backupWorkerCall/)
assert.match(backupWorkerClient, /DB_BACKUP_WORKER_URL/)
assert.match(backupWorkerClient, /Bearer /)
assert.doesNotMatch(apiCore, /pg_database_size|pg_restore|createdb|dropdb|open\(lock, 'wx'/, 'backup engine must live in the independent backup repository')
assert.match(compose, /api_state:\/var\/lib\/hanasand/)
assert.match(compose, /DB_BACKUP_WORKER_URL/)
assert.doesNotMatch(compose, /database-backup:|DB_BACKUP_SCHEDULE|DB_BACKUP_DIR/)
assert.match(apiCron, /DATABASE_BACKUP_JOB_ID/)
assert.doesNotMatch(apiCron, /runDueApiCronJob\(DATABASE_BACKUP_JOB_ID\)/, 'the backup worker owns its scheduler independently')

console.log('Backup operator workflow checks passed.')

async function source(relative: string) {
    return readFile(new URL(relative, import.meta.url), 'utf8')
}
