import { strict as assert } from 'node:assert'
import { existsSync, readFileSync } from 'node:fs'
import test from 'node:test'
import path from 'node:path'
import { sanitizeHistory } from '../src/app/browser/pageClient'

const root = process.cwd()

test('regular browser sandbox route and broker contract are wired', () => {
    const routeSource = readFileSync(path.join(root, 'src/app/sandbox/page.tsx'), 'utf8')
    const browserAliasSource = readFileSync(path.join(root, 'src/app/browser/page.tsx'), 'utf8')
    const clientSource = readFileSync(path.join(root, 'src/app/browser/pageClient.tsx'), 'utf8')
    const legacyBrowserSource = readFileSync(path.join(root, 'src/app/browser-sandbox/page.tsx'), 'utf8')
    const legacyOnionSource = readFileSync(path.join(root, 'src/app/solutions/onion-session/page.tsx'), 'utf8')
    const wsSource = readFileSync(path.join(root, '../api/src/plugins/ws.ts'), 'utf8')
    const brokerSource = readFileSync(path.join(root, '../api/src/handlers/onionSession/ws.ts'), 'utf8')
    const runsSource = readFileSync(path.join(root, '../api/src/handlers/browserSandboxRuns.ts'), 'utf8')
    const routesSource = readFileSync(path.join(root, '../api/src/routes.ts'), 'utf8')
    const analysisSource = readFileSync(path.join(root, '../api/src/handlers/onionSession/analysis.ts'), 'utf8')
    const workerDockerSource = readFileSync(path.join(root, '../api/Dockerfile'), 'utf8')
    const streamWatchdogSource = readFileSync(path.join(root, '../api/browser-worker/reconnect-watchdog.js'), 'utf8')
    const stopRunSource = clientSource.slice(clientSource.indexOf('const stopRun'), clientSource.indexOf('const resetRun'))
    const socketErrorSource = clientSource.slice(clientSource.indexOf('socket.onerror'), clientSource.indexOf('socket.onmessage'))

    assert(routeSource.includes('path: \'/sandbox\''), 'sandbox route metadata should use the canonical public route path.')
    assert(routeSource.includes('<BrowserPageClient initialData='), 'sandbox route should render the unified client.')
    assert(browserAliasSource.includes('redirect(\'/sandbox\')'), 'the old browser route should redirect to the canonical sandbox route.')
    assert(!existsSync(path.join(root, 'src/app/browser-obfuscated/page.tsx')), 'the browser obfuscation test fixture must not ship as a production route.')
    assert(!existsSync(path.join(root, 'src/app/browser-download/page.tsx')), 'the browser download test fixture must not ship as a production route.')
    assert(!existsSync(path.join(root, 'src/app/dev/vm-smoke/page.tsx')), 'the VM control test fixture must not ship as a production route.')
    assert(legacyBrowserSource.includes('redirect(\'/sandbox\')'), 'legacy regular sandbox route should redirect to the canonical sandbox route.')
    assert(legacyOnionSource.includes('redirect(\'/sandbox\')'), 'legacy onion route should redirect to the canonical sandbox route.')
    assert(clientSource.includes('Browser'), 'client should expose the URL-first browser surface.')
    assert(clientSource.includes('NEXT_PUBLIC_BROWSER_WS'), 'client should use the unified browser websocket endpoint.')
    assert(clientSource.includes('BrowserNetwork'), 'client should model Regular and Tor network modes.')
    assert(clientSource.includes('inferNetwork'), 'client should infer Tor for onion targets.')
    assert(clientSource.includes('BrowserFingerprint'), 'client should expose investigation metadata presets.')
    assert(clientSource.includes('SlidersHorizontal'), 'client should keep investigation metadata behind a compact filter control.')
    assert(clientSource.includes('VirusTotal'), 'default profile should include VirusTotal.')
    assert(clientSource.includes('urlquery'), 'default profile should include urlquery.')
    assert(clientSource.includes('WebCrack'), 'default profile should include WebCrack.')
    assert(clientSource.includes('Screenshot timeline'), 'client should expose screenshot timeline output.')
    assert(clientSource.includes('>Summary</h2>'), 'client should expose analyst summary output.')
    assert(clientSource.includes('window.localStorage.setItem'), 'client should persist saved profiles locally.')
    assert(clientSource.includes('/api/backend/browser/profiles'), 'client should sync saved profiles through the authenticated backend proxy.')
    assert(clientSource.includes('ProfileToolEditor'), 'client should expose editable custom profile tool lists.')
    assert(clientSource.includes('Profiles synced to account'), 'client should surface account profile sync state.')
    assert(clientSource.includes('credentials:') && clientSource.includes('include'), 'client profile sync should include account cookies.')
    assert(clientSource.includes('Copyable indicators'), 'client should expose copyable indicator output.')
    const analystSummarySource = clientSource.slice(clientSource.indexOf('function buildAnalystSummary'), clientSource.indexOf('function buildReviewQueue'))
    assert(!analystSummarySource.includes('networkSummary?.domains'), 'contacted domains must stay in network evidence instead of being labeled as indicators.')
    assert(!analystSummarySource.includes('sourceUrls'), 'ordinary source assets must not be labeled as indicators.')
    assert(analystSummarySource.includes('suspiciousDeobfuscationTasks.flatMap'), 'decoded indicators must come from code already assessed as suspicious.')
    assert(clientSource.includes('SandboxEvidence'), 'client should model backend-rendered sandbox evidence.')
    assert(clientSource.includes('deobfuscationTasks'), 'client should surface WebCrack-ready deobfuscation tasks.')
    assert(clientSource.includes('SandboxWebCrackLoad'), 'client should model WebCrack script injection results.')
    assert(clientSource.includes('WebCrack loaded'), 'client should summarize WebCrack script injection.')
    assert(clientSource.includes('SandboxToolAnalysis'), 'client should model parsed external-tool evidence.')
    assert(clientSource.includes('>Details</h2>'), 'client should expose an inspectable evidence workspace.')
    assert(clientSource.includes('>Tabs</h2>'), 'client should expose tabs for every configured profile tool.')
    assert(clientSource.includes('No obfuscated code was found on this page.'), 'client should describe an unnecessary WebCrack run without generic sample wording.')
    assert(clientSource.includes('pushEvent(\'Sandbox closed.\')'), 'client should keep broker implementation details out of visible activity copy.')
    assert(clientSource.includes('SandboxTabStrip'), 'client should show Browser, VirusTotal, urlquery, WebCrack, and custom tools as tabs.')
    assert(clientSource.includes('providerTabStatus'), 'client should keep provider tab statuses visible without opening lower panels.')
    assert(clientSource.includes('providerDetail'), 'client should summarize parsed provider status near the browser viewport.')
    assert(clientSource.includes('title=\'Statistics\''), 'client should retain captured run statistics.')
    assert(clientSource.includes('VirusTotal'), 'client should show VirusTotal provider status.')
    assert(clientSource.includes('urlquery'), 'client should show urlquery provider status.')
    assert(clientSource.includes('WebCrack / decoded code'), 'client should show WebCrack decoded-code status.')
    assert(clientSource.includes('Network / requests'), 'client should show network request evidence.')
    assert(clientSource.includes('Console logs'), 'client should show console and broker event evidence.')
    assert(clientSource.includes('Indicators'), 'client should show copyable indicator evidence.')
    assert(clientSource.includes('Provider unavailable') && clientSource.includes('Provider error'), 'client should render honest unavailable or failed provider states.')
    assert(clientSource.includes('Result unavailable'), 'client should render honest unavailable parsed-result states.')
    assert(clientSource.includes('VirusTotal vendors'), 'client should summarize VirusTotal vendor counts.')
    assert(clientSource.includes('urlquery alerts'), 'client should summarize urlquery alert counts.')
    assert(clientSource.includes('Community comments'), 'client should summarize community comments.')
    assert(clientSource.includes('communityComments.map'), 'provider tabs should render the actual community comment text.')
    assert(clientSource.includes('the provider did not return the text'), 'provider tabs should explain any reported comment count without returned bodies.')
    assert(clientSource.includes('Threat context'), 'client should summarize observed actor, malware, and tool context.')
    assert(clientSource.includes('URL timeline'), 'client should list the active URL for captured screenshots.')
    assert(clientSource.includes('Analyst brief'), 'client should expose a structured analyst brief.')
    assert(clientSource.includes('Recommended action'), 'client should expose a recommended analyst action.')
    assert(clientSource.includes('buildAnalystBrief'), 'client should derive verdict, impact, freshness, confidence, and next steps.')
    assert(clientSource.includes('Insufficient external evidence'), 'client should use neutral no-evidence verdict language.')
    assert(!clientSource.includes('Treat as suspicious'), 'client should not produce unsupported suspicious verdicts without real detections.')
    assert(!clientSource.includes('Treat as malicious'), 'client should not produce unsupported malicious verdicts without real detections.')
    assert(!clientSource.includes('input.threatAssociations.length || input.failedRequests'), 'failed requests alone should not make a benign/unknown run require review.')
    assert(!clientSource.includes('produced tool context from'), 'summary should not claim provider context without parsed provider results.')
    assert(!clientSource.includes('External tools loaded but did not expose'), 'summary should point to provider panel status instead of implying evidence exists.')
    assert(clientSource.includes('DOM-ready capture'), 'client should distinguish DOM-ready lifecycle screenshots.')
    assert(clientSource.includes('Loaded-page capture'), 'client should distinguish loaded-page lifecycle screenshots.')
    assert(clientSource.includes('dedupeThreatAssociations'), 'client should deduplicate threat context from page, tool, and decoded-script evidence.')
    assert(clientSource.includes('SandboxNetworkSummary'), 'client should model network telemetry from the sandbox browser.')
    assert(clientSource.includes('Network requests'), 'client should summarize request volume.')
    assert(clientSource.includes('Contacted domains'), 'client should summarize contacted domains.')
    assert(clientSource.includes('Blocked/failed requests'), 'client should summarize blocked and failed requests.')
    assert(clientSource.includes('Obfuscated scripts'), 'client should summarize obfuscated script findings.')
    assert(clientSource.includes('Suspicious captures'), 'client should summarize suspicious rendered evidence.')
    assert(clientSource.includes('Queued for sandbox capacity'), 'client should surface queued sandbox capacity state.')
    assert(!clientSource.includes('10 active browsers by default'), 'pre-run browser form should not disclose shared capacity trivia.')
    assert(clientSource.includes('CapacityPanel'), 'client should show a dedicated sandbox capacity panel.')
    assert(clientSource.includes('HistoryPanel'), 'client should expose recent run history and quota state.')
    assert(clientSource.includes('Taking longer than expected...'), 'browser should explain delayed first frames after five seconds.')
    assert(!clientSource.includes('onClick={() => undefined}') && clientSource.includes('Try again') && clientSource.includes('Contact us'), 'browser should offer delayed-run recovery actions after ten seconds.')
    assert(clientSource.includes('hanasand:open-support'), 'browser should open the support chat without navigating away.')
    assert(clientSource.includes('historyDomainKey') && clientSource.includes('Date.parse(right.startedAt) - Date.parse(left.startedAt)'), 'recent history should keep the newest scan for each normalized domain.')
    assert(clientSource.includes('/api/backend/browser/runs'), 'client should load browser run history through the backend proxy.')
    assert(routeSource.includes('/browser/stats'), 'client should load browser run stats through the backend proxy.')
    assert(clientSource.includes('runs24h') && clientSource.includes('darkwebRuns24h'), 'client should show API-backed daily run metrics.')
    assert(clientSource.includes('/api/backend/browser/profiles'), 'client should use the canonical browser profile API path.')
    assert(clientSource.includes('sessionToken: getCookie(\'access_token\')'), 'browser websocket should use the same auth token cookie as login and profile sync.')
    assert(clientSource.includes('const profileTools = selectedProfile.tools'), 'free browsing includes the selected SOC triage tools.')
    assert(clientSource.includes('Run again'), 'client should expose rerun controls for recent browser runs.')
    assert(clientSource.includes('onRerun={(run) => startRun({ target: run.target })}'), 'recent run reruns should preserve the target and let network inference choose regular or Tor.')
    assert(clientSource.includes('Interactive isolated browser viewport'), 'client should expose one interactive viewport for Regular and Tor runs.')
    assert(clientSource.includes('type: \'click\''), 'client should forward frame clicks to the remote browser.')
    assert(clientSource.includes('type: \'wheel\''), 'client should forward frame wheel input to the remote browser.')
    assert(clientSource.includes('type: \'key\''), 'client should forward keyboard input to the remote browser.')
    assert(clientSource.includes('type: \'clipboard\''), 'client should forward analyst clipboard paste into the remote browser.')
    assert(clientSource.includes('Remote console:'), 'client should surface remote console output in the event stream.')
    assert(clientSource.includes('capacity_busy'), 'client should react to backend capacity-busy events.')
    assert(clientSource.includes('capacity_admitted'), 'client should react when a queued sandbox is admitted.')
    assert(clientSource.includes('durationSeconds: quota?.sessionSeconds || 300'), 'browser runs should use the server plan duration with a five-minute free default.')
    assert(stopRunSource.includes('type: \'end\'') && !stopRunSource.includes('.close()'), 'Stop should wait for the worker ended acknowledgement instead of racing the websocket closed.')
    assert(!socketErrorSource.includes('setSessionState(\'failed\')'), 'a transport error alone must not misclassify a completed browser run as failed.')
    assert(clientSource.includes('payload.type === \'ended\'') && clientSource.includes('current === \'failed\' || current === \'unreachable\' ? current : failed ? \'failed\' : \'ended\''), 'the worker ended message should authoritatively complete the frontend run.')
    assert(clientSource.includes('label=\'Time left\'') && clientSource.includes('role=\'timer\''), 'mobile analysts should see an explicit live countdown.')
    assert(clientSource.includes('aria-label=\'Back to top\'') && clientSource.includes('sticky top-0'), 'mobile run controls should remain reachable above the interactive stream.')
    assert(!clientSource.includes('onLoad={() => scrollRouteFrameToTop(\'auto\')}'), 'stream readiness must not steal the page scroll position.')
    assert(!clientSource.includes('new ResizeObserver(sendBrowserResize)'), 'responsive product layout changes must not resize an established remote stream.')
    assert(clientSource.includes('title={activeViewportUrl}>{historyDomainKey(activeViewportUrl)}</h1>'), 'show the domain as the heading and retain the full URL in its title.')
    assert(clientSource.includes('type: \'select_tab\''), 'provider tab selection should switch the real remote Chromium tab.')
    assert(clientSource.includes('statusState === \'tab_selected\'') && clientSource.includes('setActiveSandboxTab(remoteTabId)'), 'native Chromium tab changes should update the outer tab strip.')
    assert(clientSource.includes('remoteTabUrls[activeTool.id]'), 'the outer address bar should follow the active remote provider tab URL.')
    assert(clientSource.includes('type: \'extend\''), 'client should request authoritative run extensions from the worker.')
    assert(clientSource.includes('Add 5 min · Paid'), 'client should expose the second five-minute extension as a paid option.')
    assert(clientSource.indexOf('{streamUrl ? (') < clientSource.indexOf('activeTool && activeToolCapture'), 'the persistent WebRTC stream should take precedence over static provider evidence.')
    assert.equal(clientSource.split('<EvidenceWorkspace ').length - 1, 1, 'show one investigation result below the browser without moving the stream on run completion.')
    assert(clientSource.includes('Connection and provider details'), 'secondary runtime details should remain available without competing with the browser controls.')

    assert(wsSource.includes('/api/ws/browser/:id'), 'API websocket plugin should register the unified browser route.')
    assert(wsSource.includes('/api/ws/browser-sandbox/:id'), 'API websocket plugin should register the regular sandbox route.')
    assert(wsSource.includes('handleOnionSessionSocket(worker, req.params.id, \'regular\')'), 'regular sandbox route should force regular network mode.')
    assert(wsSource.includes('requestBrowserAdmission(id') && wsSource.includes('releaseAdmission?.()'), 'the API broker should enforce and release fleet-wide isolated-browser capacity.')
    assert(wsSource.includes('if (payload?.type !== \'start\') return'), 'the isolated worker must not launch or bypass run preparation before a valid start message.')
    assert(wsSource.includes('Promise.all([admission.promise, streamResolution])') && wsSource.includes('BROWSER_STREAM_RESOLUTION=${resolution}'), 'the worker display resolution should be fixed before WebRTC starts.')
    assert(wsSource.includes('connection.ping()') && wsSource.includes('20_000'), 'WebRTC signalling should stay alive through reverse-proxy idle windows.')
    assert(wsSource.includes('browser_run_client_closed') && wsSource.includes('finishBrowserRun(id, \'ended\')'), 'client disconnects should be logged and leave a terminal database run.')
    assert(wsSource.includes('browser_stream_disconnected'), 'unexpected WebRTC signalling closures should be recorded for diagnosis.')
    assert(wsSource.includes('currentBrowserAdmissionStatus()'), 'worker status should be rewritten with fleet-wide broker capacity.')
    assert(brokerSource.includes('network?: \'tor\' | \'regular\''), 'broker should support regular network mode.')
    assert(brokerSource.includes('DEFAULT_BROWSER_MAX_SESSIONS = 100'), 'broker should default shared browser capacity to one hundred active sessions.')
    assert(!brokerSource.includes('network === \'regular\' ? requestBrowserAdmission'), 'broker should use the shared queue for Regular and Tor runs.')
    assert(brokerSource.includes('BROWSER_SANDBOX_MAX_SESSIONS'), 'broker capacity should be configurable by environment.')
    assert(routesSource.includes('/browser/profiles'), 'API should expose canonical browser profile routes.')
    assert(runsSource.includes('quota.active >= quota.concurrentLimit') && runsSource.includes('pg_advisory_xact_lock'), 'browser starts should enforce simultaneous sessions atomically.')
    assert(!runsSource.includes('consumeBillingQuota') && runsSource.includes('limit: null'), 'completed runs must not exhaust browser access.')
    assert(wsSource.includes('browserStartOptions(payload, result.quota)'), 'the broker must apply server-side paid feature limits.')
    assert(routesSource.includes('/browser/runs'), 'API should expose browser run history routes.')
    assert(routesSource.includes('/browser/stats'), 'API should expose browser run stats.')
    assert(runsSource.includes('tokenWrapper(req, res)'), 'browser report access checks must use the real response for session authentication.')
    assert(routesSource.includes('/support/tickets') && routesSource.includes('/support/tickets/:id/messages'), 'API should expose support ticket and message routes.')
    assert(runsSource.includes('INTERVAL \'24 hours\'') && runsSource.includes('network = \'tor\''), 'browser stats should count rolling daily regular and darkweb runs.')
    assert(runsSource.includes('5_000'), 'browser stats should use a five-second in-process cache.')
    assert(brokerSource.includes('capacity_busy'), 'broker should queue overflow regular sandbox sessions.')
    assert(brokerSource.includes('capacity_admitted'), 'broker should admit queued sessions when capacity frees.')
    assert(brokerSource.includes('profileTools'), 'broker should accept saved-profile tool URLs.')
    assert(brokerSource.includes('tool_capture'), 'broker should emit profile tool captures.')
    assert(brokerSource.includes('provider capture started'), 'broker should emit provider progress before long external-tool waits.')
    assert(brokerSource.includes('BROWSER_SANDBOX_PROVIDER_TABS') && brokerSource.includes('=== \'0\''), 'broker should run external provider tabs by default with an explicit opt-out.')
    assert(clientSource.includes('hasParsedProviderResult'), 'client should not treat unknown placeholder provider rows as parsed external evidence.')
    assert(brokerSource.includes('clickExactConsentAction') && brokerSource.includes('godta alle'), 'broker should explicitly click common consent accept buttons before hiding cookie overlays.')
    assert(brokerSource.includes('const initialEvidence = enrichProviderEvidence(await withTimeout(collectPageEvidence(toolPage)') && brokerSource.includes('providerPendingEvidence(toolPage.url() || toolUrl'), 'broker should emit provider DOM-ready captures before deeper readiness parsing.')
    assert(brokerSource.includes('void captureProfileTools(') && brokerSource.includes('message.profileTools || []') && brokerSource.includes('cachedDeobfuscationTasks'), 'broker should capture provider tools in the background after the browser is live.')
    assert(brokerSource.includes('capturedAt'), 'broker should emit screenshot timestamps.')
    assert(brokerSource.includes('page.on(\'framenavigated\''), 'broker should capture active URL changes and redirects.')
    assert(brokerSource.includes('page.on(\'domcontentloaded\''), 'broker should capture DOM-ready state changes.')
    assert(brokerSource.includes('page.on(\'load\''), 'broker should capture fully loaded state changes.')
    assert(brokerSource.includes('initial_target'), 'broker should capture the initial target after navigation settles.')
    assert(brokerSource.includes('collectPageEvidence'), 'broker should extract rendered page evidence.')
    assert(brokerSource.includes('analyzeToolEvidence'), 'broker should parse VirusTotal/urlquery-style tool evidence.')
    assert(brokerSource.includes('providerCommunityComments') && brokerSource.includes('/comments?limit=8'), 'broker should collect structured VirusTotal community comment bodies.')
    assert(brokerSource.includes('toolAnalysis'), 'broker should emit parsed tool analysis.')
    assert(brokerSource.includes('summarizeNetworkEvents'), 'broker should summarize sandbox network telemetry.')
    assert(brokerSource.includes('networkSummary'), 'broker should emit network summaries with frames.')
    assert(brokerSource.includes('inspectDownload(download)') && brokerSource.includes('downloads.length >= 10'), 'downloads must remain bounded and inspected inside the sandbox.')
    assert(brokerSource.includes('sandboxUrlSafety'), 'broker should enforce URL safety before navigation and redirects.')
    assert(brokerSource.includes('unsafe_target_blocked'), 'broker should report blocked unsafe submitted targets.')
    assert(brokerSource.includes('unsafe_request_blocked'), 'broker should abort unsafe redirected or subresource requests.')
    assert(analysisSource.includes('metadata.google.internal'), 'analysis helpers should block cloud metadata hostnames.')
    assert(analysisSource.includes('private or local network address'), 'analysis helpers should block private, loopback, link-local, and multicast addresses.')
    assert(brokerSource.includes('obfuscatedScripts'), 'broker should identify obfuscated script candidates.')
    assert(brokerSource.includes('deobfuscationTasks'), 'broker should emit WebCrack-ready script samples.')
    assert(brokerSource.includes('loadWebCrackSample'), 'broker should load extracted obfuscated script samples into WebCrack.')
    assert(brokerSource.includes('webcrackLoad'), 'broker should emit WebCrack load results.')
    assert(clientSource.includes('capturedToolCount'), 'client should count unique configured profile tools instead of duplicate provider update captures.')
    assert(clientSource.includes('isUsefulFrameImage') && clientSource.includes('image.length > 24_000'), 'client should not promote tiny blank frames over useful browser captures.')
    assert(clientSource.includes('setActiveImage(image)'), 'client should promote useful browser frames, including manual consent or challenge screens.')
    assert(analysisSource.includes('decodedPreview'), 'analysis helpers should include decoded previews for obfuscated scripts.')
    assert(analysisSource.includes('decoded network indicators'), 'analysis helpers should assess decoded network indicators.')
    assert(brokerSource.includes('extractIndicators'), 'broker should extract domains, IPs, and URLs for later-stage analysis.')
    assert(analysisSource.includes('THREAT_ASSOCIATION_TERMS'), 'analysis helpers should carry a curated actor and malware context dictionary.')
    assert(brokerSource.includes('extractThreatAssociations'), 'broker should extract observed threat context from rendered, tool, and decoded evidence.')
    assert(brokerSource.includes('DEFAULT_DURATION_MS = 90 * 1000'), 'worker should enforce the ninety-second default deadline.')
    assert(brokerSource.includes('SUSPICIOUS_DURATION_MS = 3 * 60 * 1000'), 'worker should extend suspicious runs to at least three minutes.')
    assert(brokerSource.includes('MANUAL_EXTENSION_MS = 5 * 60 * 1000'), 'worker should add five minutes per approved manual extension.')
    assert(brokerSource.includes('toolPages.set(toolId, toolPage)') && !brokerSource.includes('await toolPage.close().catch'), 'provider pages should remain open as interactive remote tabs for the run lifetime.')
    assert(brokerSource.includes('__hanasandRemoteTabSelected') && brokerSource.includes('document.visibilityState') && brokerSource.includes('trace(\'native_tab_selected\''), 'the broker should observe and log native Chromium tab selection inside the WebRTC stream.')
    assert(brokerSource.includes('trace(\'provider_tab_navigated\''), 'provider redirects should be traceable separately from native tab selection.')
    assert(wsSource.includes('browserPaidExtensionAllowed') && wsSource.includes('payload.paidAuthorized = true'), 'main API should authorize paid extensions before forwarding them to isolated workers.')
    assert(runsSource.includes('browserPaidExtensionAllowed'), 'browser subscription data should control the paid extension entitlement.')
    assert(runsSource.includes('status IN (\'failed\', \'unreachable\')'), 'generic ended cleanup must preserve explicit failed and unreachable terminal states.')
    assert(workerDockerSource.includes('reconnect-watchdog.js') && streamWatchdogSource.includes('player.status === \'connected\''), 'a stuck Selkies viewer should recover without restarting the remote browser.')
    assert(analysisSource.includes('tool_context'), 'analysis helpers should tag threat context found in external tool pages.')
    assert(analysisSource.includes('decoded_script'), 'analysis helpers should tag threat context found in decoded scripts.')
})

test('recent browser history keeps the newest scan for each domain', () => {
    const history = sanitizeHistory([
        { id: 'first-vg', target: 'https://www.vg.no/first', network: 'regular', status: 'ended', startedAt: '2026-07-14T05:00:00.000Z' },
        { id: 'example', target: 'https://example.com/', network: 'regular', status: 'ended', startedAt: '2026-07-14T05:30:00.000Z' },
        { id: 'latest-vg', target: 'https://vg.no/latest', network: 'regular', status: 'ended', startedAt: '2026-07-14T06:00:00.000Z' },
    ])

    assert.deepEqual(history.map(run => run.id), ['latest-vg', 'example'])
})
