import { expect, test } from '@playwright/test'

test('organization profiles require membership and owner account tools remain private', async ({ browser, baseURL }) => {
    test.skip(process.env.PROFILE_NAVIGATION_TEST !== '1', 'Requires the isolated profile fixture.')
    test.setTimeout(60000)
    expect(baseURL).toBe('http://127.0.0.1:3230')
    const context = await browser.newContext({ viewport: { width: 1440, height: 900 } })
    await context.addCookies(['id', 'name', 'access_token'].map(name => ({ name, value: 'role-fixture-admin', url: baseURL! })))
    const page = await context.newPage()
    await page.goto('/management')
    await page.getByRole('heading', { name: 'Selected Person', exact: true }).click()
    await expect(page).toHaveURL(/\/profile\/selected-person$/)
    await expect(page.getByRole('heading', { name: 'Selected Person', exact: true })).toBeVisible()
    await expect(page.getByText('Member', { exact: true })).toHaveCount(0)
    await expect(page.getByText('@selected-person', { exact: true })).toBeVisible()
    await expect(page.locator('[aria-label="Dashboard sidebar"]')).toHaveCount(1)
    await expect(page.getByRole('heading', { name: 'Certificates', exact: true })).toHaveCount(0)
    await page.screenshot({ path: '/tmp/selected-user-profile.png' })
    await page.reload()
    await expect(page.getByRole('heading', { name: 'Selected Person', exact: true })).toBeVisible()
    for (const width of [390, 768, 1440]) {
        await page.setViewportSize({ width, height: 900 })
        await expect(page.getByRole('heading', { name: 'Selected Person', exact: true })).toBeVisible()
        await expect(page.locator('[aria-label="Dashboard sidebar"]')).toHaveCount(1)
        expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
    }
    await page.goto('/profile/role-fixture-admin')
    await expect(page.getByRole('heading', { name: 'Fixture Admin', exact: true })).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Certificates', exact: true })).toHaveCount(0)
    await page.getByRole('navigation', { name: 'Account pages' }).getByRole('link', { name: 'Certificates', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Certificates', exact: true })).toBeVisible()
    await expect(page.locator('[aria-label="Dashboard sidebar"]')).toHaveCount(1)
    await context.close()
    const visitor = await browser.newContext()
    const publicPage = await visitor.newPage()
    for (const profile of ['selected-person', 'sindre', 'eirikhanasand']) {
        const publicResponse = await publicPage.goto(`/profile/${profile}`)
        expect(publicResponse?.status()).toBe(404)
    }
    const keyResponse = await publicPage.goto('/profile/eirikhanasand/ssh-keys')
    expect(keyResponse?.status()).toBe(200)
    const loginUrl = new URL(publicPage.url())
    expect(loginUrl.pathname).toBe('/login')
    expect(loginUrl.searchParams.get('path')).toBe('/profile/eirikhanasand/ssh-keys')
    await visitor.close()
})
