import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'

function readOptional(url: URL) {
    return existsSync(url) ? readFileSync(url, 'utf8') : ''
}

const ws = readFileSync(new URL('../src/plugins/ws.ts', import.meta.url), 'utf8')
const rateLimit = readFileSync(new URL('../src/plugins/rateLimit.ts', import.meta.url), 'utf8')
const index = readFileSync(new URL('../src/index.ts', import.meta.url), 'utf8')
const onionWs = readFileSync(new URL('../src/handlers/onionSession/ws.ts', import.meta.url), 'utf8')
const dockerfile = readFileSync(new URL('../Dockerfile', import.meta.url), 'utf8')
const stackVerifier = readFileSync(new URL('../../scripts/verify-stack-release.sh', import.meta.url), 'utf8')
const appRuntimeStage = /FROM oven\/bun:1\.3\.13-alpine AS app-runtime-base\n([\s\S]*?)\nFROM app-runtime/.exec(dockerfile)?.[1] || ''
const handoff = readOptional(new URL('../../agents/scripts/handoff-context.mjs', import.meta.url))
const runbook = readOptional(new URL('../../agents/HANDOFF_RUNBOOK.md', import.meta.url))
const composeUrl = new URL('../../docker-compose.yml', import.meta.url)

assert.match(ws, /BROWSER_SANDBOX_ALLOW_SHARED_WORKER !== 'development'/, 'browser proxy should require per-session workers unless an explicit development override is set')
assert.doesNotMatch(ws, /BROWSER_SANDBOX_PER_SESSION_WORKER !== '0'/, 'browser proxy should not expose a production-safe switch back to shared workers')
assert.match(ws, /if \(process\.env\.BROWSER_SANDBOX_WORKER_ONLY === '1'\) \{\s*registerBrowserSessionRoutes\(fastify\)\s*return\s*\}/, 'browser-worker-only API process should register only browser websocket routes')
assert.match(ws, /function registerBrowserSessionRoutes/, 'browser routes should be isolated so worker-only mode can keep a small route surface')
assert.doesNotMatch(ws, /#constants/, 'browser websocket plugin should not import the full app constants module in browser-worker-only processes')
assert.doesNotMatch(ws, /import \{ handleMessage \}/, 'browser websocket plugin should not import share DB handlers before worker-only route narrowing')
assert.doesNotMatch(ws, /import \{ enqueueLoadTestRun, startLoadTestQueue \}/, 'browser websocket plugin should not import load-test DB handlers before worker-only route narrowing')
assert.match(index, /browserWorkerOnly[\s\S]*service: 'browsers'[\s\S]*IndexHandler/, 'browser-only root endpoint should be a small health response instead of exposing the API route table')
assert.match(onionWs, /process\.env\.NODE_ENV !== 'production' && process\.env\.BROWSER_SANDBOX_ALLOW_LOCAL_TARGETS === '1'/, 'local target override should be unavailable in production')
assert.match(ws, /createRuntimeContainer/, 'browser proxy should create an isolated worker container')
assert.match(ws, /randomUUID\(\)\.slice\(0, 8\)/, 'browser session worker container names should stay fresh even if a session id is reused')
assert.match(ws, /connectResumableWorker/, 'browser proxy should use a recoverable worker connection')
assert.match(readFileSync(new URL('../src/utils/ws/resumableWorker.ts', import.meta.url), 'utf8'), /await connectBrowserWorkerSocket/, 'browser proxy should wait for the worker websocket before failing the session')
assert.match(ws, /BROWSER_SANDBOX_WORKER_IMAGE \|\| 'hanasand_browsers:latest'/, 'ephemeral workers should use the independently released browser image')
assert.match(ws, /BROWSER_SANDBOX_WORKER_NETWORK \|\| 'hanasand_browsernet'/, 'ephemeral workers should fall back to the dedicated browser network')
assert.doesNotMatch(ws, /BROWSER_SANDBOX_WORKER_NETWORK \|\| 'hanasand_hanasandnet'/, 'ephemeral workers must not fall back to the app network')
assert.match(ws, /BROWSER_SANDBOX_EGRESS_FIREWALL_READY !== '1'/, 'production browser sessions should fail closed until the host egress firewall is marked ready')
assert.match(ws, /assertBrowserWorkerEgress\(\)\s*const warm =/, 'prestarted claims must preserve the production egress firewall gate')
assert.match(ws, /Shared browser worker is disabled; isolated per-session workers are required in production\./, 'main API should fail closed instead of running a browser locally when shared worker config is missing')
assert.match(ws, /function sendErrorThenClose/, 'browser proxy should flush startup errors to the client before closing the websocket')
assert.match(ws, /connection\.send\(JSON\.stringify\(\{ type: 'error', message \}\), \(\) =>/, 'browser proxy should not race error delivery against websocket close')
assert.match(onionWs, /Production browser sessions must run in isolated browser workers\./, 'browser handler should reject production launches outside worker-only containers')
assert.match(onionWs, /Production browser workers require Chromium sandbox\./, 'browser handler should require Chromium sandbox in production workers')
assert.match(onionWs, /process\.env\.NODE_ENV !== 'production' && process\.env\.BROWSER_SANDBOX_PREWARM !== '0'/, 'browser prewarm should be unavailable in production API containers')
assert.doesNotMatch(onionWs, /process\.env\.NODE_ENV === 'production'[\s\S]{0,120}regularBrowser\(\)/, 'production code should not prewarm Chromium in the main API process')
assert.doesNotMatch(onionWs, /sandboxDnsSafetyCache/, 'DNS safety should not cache successful host checks because that permits DNS rebinding')
assert.match(onionWs, /serviceWorkers:\s*'block'/, 'browser context should block service workers so request safety routing cannot be bypassed')
assert.match(onionWs, /context\.route\('\*\*\/\*'/, 'request safety routing should apply to all context pages, including provider tabs')
assert.doesNotMatch(onionWs, /page\.route\('\*\*\/\*'/, 'request safety routing should not be limited to the initial target page')
assert.match(ws, /Init:\s*true/, 'session worker should run with Docker init enabled')
assert.match(ws, /Privileged:\s*false/, 'session worker should explicitly disable privileged mode')
assert.match(ws, /IpcMode:\s*'private'/, 'session worker should use a private IPC namespace')
assert.match(ws, /ReadonlyRootfs:\s*true/, 'session worker root filesystem should be read-only')
assert.match(ws, /CapAdd:\s*\[\]/, 'session worker should not add Linux capabilities')
assert.match(ws, /CapDrop:\s*\['ALL'\]/, 'session worker should drop Linux capabilities')
assert.match(ws, /PidsLimit:\s*512/, 'session worker should cap process creation')
assert.match(ws, /NanoCpus:\s*3_000_000_000/, 'session worker should cap at the benchmarked three-core ceiling')
assert.match(ws, /browserWorkerSeccompProfile/, 'session worker should load the bundled seccomp profile')
assert.match(ws, /SecurityOpt:\s*\[`seccomp=\$\{browserWorkerSeccompProfile\}`,\s*'apparmor=docker-default',\s*'no-new-privileges'\]/, 'session worker should keep seccomp, AppArmor, and no-new-privileges')
assert.match(ws, /BROWSER_SANDBOX_WORKER_ONLY=1/, 'session worker should boot in browser-worker-only mode')
assert.match(ws, /BROWSER_SANDBOX_MAX_SESSIONS=1/, 'session worker should enforce one browser session per container')
assert.match(ws, /AutoRemove:\s*true/, 'session worker should auto-remove so failed malicious sessions do not linger after Docker exits them')
assert.doesNotMatch(ws, /DB_PASSWORD=|VM_API_TOKEN=|MAIL_ADMIN_PASSWORD=|API_SSH_KEY=|\/var\/run\/docker\.sock|lxd\/unix\.socket/, 'session worker should not receive app secrets or host control sockets')
assert.doesNotMatch(dockerfile, /browser-runtime|google-chrome-stable/, 'site image builds should not build the separately released browser image')
assert.match(ws, /SELKIES_ENCODER=x264enc/, 'browser worker should use low-latency H.264 for 60 FPS software encoding')
assert.match(ws, /SELKIES_FRAMERATE=60/, 'browser worker should target 60 FPS streaming')
assert.match(ws, /SELKIES_KEYFRAME_DISTANCE=1/, 'browser video must periodically recover from lost reference frames')
assert.match(ws, /SELKIES_CONGESTION_CONTROL=true/, 'browser stream should adapt bitrate to cellular congestion')
assert.match(onionWs, /resizeBrowserDisplay\(viewport\)/, 'the captured X display should follow the selected browser resolution')
assert.match(ws, /type: 'stream_ready'[\s\S]*transport: 'webrtc'/, 'browser proxy should announce the WebRTC transport to the client')
assert.doesNotMatch(onionWs, /setInterval\([\s\S]{0,120}sendFrame/, 'Playwright screenshots must not drive the live rendering loop')
assert.match(rateLimit, /isBrowserStreamPath\(path\)/, 'token-protected WebRTC stream assets should not exhaust the generic REST rate limit')
assert.match(rateLimit, /path\.startsWith\('\/api\/browser-stream\/'\)/, 'only browser stream routes should receive the WebRTC asset rate-limit exemption')
assert.doesNotMatch(appRuntimeStage, /\b(chromium|xvfb)\b/, 'main API image should not install Chromium or Xvfb')
assert.doesNotMatch(`${handoff}\n${runbook}`, /docker compose[^\n]*build[^\n]*browsers/, 'site handoff instructions should not rebuild browser workers')
if (existsSync(composeUrl)) {
    const compose = readFileSync(composeUrl, 'utf8')
    const serviceBlock = (name: string) => new RegExp(`\\n {2}${name}:\\n([\\s\\S]*?)(?=\\n {2}[a-zA-Z0-9_-]+:\\n|\\nvolumes:)`).exec(compose)?.[1] || ''
    assert.doesNotMatch(compose, /BROWSER_SANDBOX_PER_SESSION_WORKER/, 'compose should not expose a production switch back to shared browser workers')
    assert.match(compose, /BROWSER_SANDBOX_WORKER_NETWORK:\s*\$\{BROWSER_SANDBOX_WORKER_NETWORK:-hanasand_browsernet\}/, 'ephemeral browser workers should not join the app network by default')
    assert.match(serviceBlock('api'), /BROWSER_SANDBOX_EGRESS_FIREWALL_READY:\s*\$\{BROWSER_SANDBOX_EGRESS_FIREWALL_READY:-0\}/, 'API should receive the browser egress firewall readiness gate from compose env')
    assert.doesNotMatch(serviceBlock('api'), /BROWSER_SANDBOX_WORKER_WS/, 'API should not default to a shared browser worker websocket in production')
    assert.doesNotMatch(compose, /^  (?:browsers|browser-turn):$/m, 'browser workers and TURN should be owned by their independent Compose files')
    assert.match(stackVerifier, /verify_independent_container hanasand_browsers hanasand-browsers browsers/, 'site release must preserve the browser Compose project')
    assert.match(stackVerifier, /verify_independent_container hanasand_browser_turn hanasand-browser-turn browser-turn/, 'site release must preserve the TURN Compose project')
    assert.match(compose, /BROWSER_SANDBOX_PREWARM:\s*"0"/, 'compose should not prewarm Chromium in the privileged API container')
    assert.match(compose, /browsernet:\s*\n\s*name:\s*hanasand_browsernet/, 'compose should define a dedicated browser worker network')
    assert.match(serviceBlock('api'), /networks:[\s\S]*?(?:- browsernet\b|browsernet:)/, 'API should join the browser network only for the worker websocket control path')
    assert.doesNotMatch(serviceBlock('postgres'), /- browsernet/, 'database should not join the browser worker network')
    assert.doesNotMatch(serviceBlock('stalwart'), /- browsernet/, 'mail service should not join the browser worker network')
}

console.log('Browser per-session worker isolation contract passed.')
